apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:jgP3SB2ZqBUYBTHFkKIg/ZWFKAKnLNwLq9XrV1f8CtgOuVPTssTsgqTdz6WxDu6nSnt5mrPwT5gOOaCVYinEvSKO5egsCnKXB4H0CxL9IarrhDIWAFyeGBb0ocPahYa/xxSkWLu/czvhOduqyF7bbxYF31IyNnQxBHmVvIKiXZ5Vu0G2kbLRTEduelFbSMo7BS6Fhh4pHK3xFhKJWZK+wonhgDlz7YSTwWuoD8T5FW3aW3KzieljqGv0Pxz/GrKcNWTLh8EfOO6xIVU48S+7pDioiRRekQZR,iv:C9C8WqEJkJ7zdsEisV+9357GNmEacRtPL3OS7zTKQjg=,tag:ku/k9MPFOMJOh6HGqjTXFw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t7jkfgauf44wj2l5uz9h7rcgtdnatssqc3cv8fjl8mcrj5t3gaaqzmkfhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbktCbjRRbnBON21Rcjgr
            SDNldDFRdjFkTlQvWXdzOW5EVkxhdlFlUWtNClZUdDY1NC81MXBRTU1NTFZHQ1hF
            UU9sUmdKUWhNR25qVmNEOGx5OU9vbDQKLS0tIDcvSTFYWW8vVHcxUU5seWF6eFJr
            NEk1M09GZm1TdlluQ0lvUms2eFBia1UKmZxnwp2vxdzxJtctRAi+7l+EWC+JTo6g
            fbt4avUHjiGU90riAdDY3osg8+QlKGj6FOtdMi/NHn7H2EE57vU11w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T12:53:50Z"
    mac: ENC[AES256_GCM,data:yDNleSOBYveVf2YiB5IsuztBnV57Md0+1wIap/yiQE72GKpNJfUHvTNgx4KbY/tphwUsHLKn/5tngPlcRkgk/LpNE5LNRnOL6p+puja+94JQcXoSBVidA0RTaWSpV3j6LGh/5g2Ch603Llbs4QJ+zlylf5Srxz5dtgHRPRprEMg=,iv:VL1bHUmKYQdlAcKwSwWKav7Ang8BCQVCShJutdkogTU=,tag:k50n+a5e+NQ8l94uWYJ+6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
